CREATE DATABASE todo_app;
CREATE TABLE todos (
    TASK_ID INT AUTO_INCREMENT PRIMARY KEY,
    TASK_DONE VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
SELECT * FROM todos;
INSERT INTO todos(TASK_ID,TASK_DONE,CREATED_AT) values('1','BOM1','2024-11-12 08:49:43 +0000');
SELECT * FROM todos;